services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    networks:
      - observability
  jaeger:
    image: jaegertracing/jaeger:2.0.0-rc2
    ports:
      - "16686:16686" # Web UI
    volumes:
      - "./jaeger/jaeger-v2-config.yml:/etc/jaeger/config.yml"
    command: ["--config", "/etc/jaeger/config.yml"]
    networks:
      observability:
        aliases: [spm_metrics_source]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Web UI
    networks:
      - observability
networks:
  observability:
